# Only works with properly configured Firebird Server v. 3.0
#spring:
#  datasource:
#    driver-class-name: org.firebirdsql.jdbc.FBDriver
#    url: jdbc:firebirdsql://localhost:3050/@basedir@/src/main/resources/db/USERS.FDB
#    username: SYSDBA
#    password: masterkey
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.FirebirdDialect
#    show-sql: true